# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI Quality Check

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ actions-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

# Setup
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11.0.2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permission for Github Actions Workflows
      run: chmod -R ug+x .github/workflow_scripts

# TODO: Move this below Quality Checks
# Sign and Build
    - name: Decrypt GPG key (To sign artifacts)
      env:
        GPG_AES256_PASSPHRASE: ${{ secrets.GPG_AES256_PASSPHRASE }}
      run: .github/workflow_scripts/decrypt_gpg_key.sh
    - name: Sign Artifacts
      env:
        # GPG_KEY_LOCATION: Not set here, it is set by the decrypt_gpg_key.sh script above
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: .github/workflow_scripts/sign_archives.sh

# Quality Checks
    - name: ShellCheck PyAtlas
      run: shellcheck pyatlas/*.sh
    - name: Quality checks (No tests)
      run: ./gradlew jar check -x test -x integrationTest
    - name: Tests
      run: ./gradlew check
    - name: Sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PR_DECORATION_GITHUB_TOKEN: ${{ secrets.SONAR_PR_DECORATION_GITHUB_TOKEN }}
      run: .github/workflow_scripts/sonar.sh



# Publish
